import { Ionicons } from "@expo/vector-icons";
import { Stack } from "expo-router";
import { Alert, Linking, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
const REPOSITORY_URL="https://github.com/puneet211086/timesheet-mobile";
const ISSUES_URL="https://github.com/puneet211086/timesheet-mobile/issues";
async function openUrl(url:string){const supported=await Linking.canOpenURL(url);if(!supported){Alert.alert("Unable to open link","Please try again later.");return;}await Linking.openURL(url);}
export default function SupportScreen(){return <SafeAreaView style={styles.safeArea}><Stack.Screen options={{title:"Support"}}/><ScrollView contentContainerStyle={styles.container}>
<View style={styles.heroIcon}><Ionicons name="help-circle-outline" size={31} color="#2563EB"/></View><Text style={styles.title}>How can we help?</Text><Text style={styles.subtitle}>Review common troubleshooting steps or report a reproducible issue.</Text>
<SupportItem icon="refresh-outline" title="Refresh the app" description="Close and reopen the app, or restart Expo with a cleared Metro cache during development."/>
<SupportItem icon="cloud-upload-outline" title="Protect important records" description="Export important timesheets as PDF or CSV before reinstalling or deleting the app."/>
<SupportItem icon="notifications-outline" title="Reminder not appearing" description="Confirm notifications are enabled in iPhone Settings and that forgotten clock-out reminders are enabled in the app."/>
<Pressable accessibilityRole="link" onPress={()=>void openUrl(ISSUES_URL)} style={({pressed})=>[styles.primaryButton,pressed&&styles.pressed]}><Ionicons name="bug-outline" size={20} color="#FFFFFF"/><Text style={styles.primaryButtonText}>Report an issue on GitHub</Text></Pressable>
<Pressable accessibilityRole="link" onPress={()=>void openUrl(REPOSITORY_URL)} style={({pressed})=>[styles.secondaryButton,pressed&&styles.pressed]}><Ionicons name="logo-github" size={20} color="#2563EB"/><Text style={styles.secondaryButtonText}>View project information</Text></Pressable>
<View style={styles.notice}><Ionicons name="mail-outline" size={20} color="#475569"/><Text style={styles.noticeText}>Before publishing, replace or supplement GitHub support with a dedicated support webpage and support email address.</Text></View>
</ScrollView></SafeAreaView>}
function SupportItem({icon,title,description}:{icon:keyof typeof Ionicons.glyphMap;title:string;description:string}){return <View style={styles.item}><View style={styles.itemIcon}><Ionicons name={icon} size={21} color="#2563EB"/></View><View style={styles.itemCopy}><Text style={styles.itemTitle}>{title}</Text><Text style={styles.itemDescription}>{description}</Text></View></View>}
const styles=StyleSheet.create({safeArea:{flex:1,backgroundColor:"#F7F8FC"},container:{padding:22,paddingBottom:44},heroIcon:{width:58,height:58,borderRadius:18,backgroundColor:"#EFF6FF",alignItems:"center",justifyContent:"center",marginTop:14},title:{color:"#0F172A",fontSize:29,fontWeight:"800",marginTop:18},subtitle:{color:"#64748B",fontSize:15,lineHeight:22,marginTop:8,marginBottom:12},item:{flexDirection:"row",backgroundColor:"#FFFFFF",borderRadius:18,padding:16,marginTop:12},itemIcon:{width:42,height:42,borderRadius:13,backgroundColor:"#EFF6FF",alignItems:"center",justifyContent:"center",marginRight:13},itemCopy:{flex:1},itemTitle:{color:"#0F172A",fontSize:16,fontWeight:"800"},itemDescription:{color:"#64748B",fontSize:13,lineHeight:19,marginTop:4},primaryButton:{minHeight:52,borderRadius:15,backgroundColor:"#2563EB",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:9,marginTop:24},primaryButtonText:{color:"#FFFFFF",fontSize:15,fontWeight:"800"},secondaryButton:{minHeight:52,borderRadius:15,borderWidth:1,borderColor:"#BFDBFE",backgroundColor:"#EFF6FF",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:9,marginTop:12},secondaryButtonText:{color:"#2563EB",fontSize:15,fontWeight:"800"},notice:{flexDirection:"row",gap:10,backgroundColor:"#EEF2F7",borderRadius:16,padding:15,marginTop:20},noticeText:{flex:1,color:"#475569",fontSize:13,lineHeight:19},pressed:{opacity:0.76}});
